[package]
name = "kakaotalk-db-decryptor"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
sha1 = "0.10.6"
cbc = "0.1.2"
base64 = "0.22.1"
pkcs12 = { version = "0.1.0", features = ["kdf"] }
